### ISSUE TITLE
Issue with getLatestVersion()

### ISSUE THREAD

**Issue by sukumardv3101** [kimxogus/react-native-version-check#24] opened 2018-01-24 06:17 UTC
getLatestVersion is returning older version than the current version.

actually app-store version of the app is 1.0.8 and is returning 1.0.6.

here is my code:

if(Platform.OS === 'ios'){
            VersionCheck.setAppID(13**********);                    // Your App ID for App Store URL
            VersionCheck.setAppName('App name'); 
        }

VersionCheck.getLatestVersion({
            provider: 'store'
          })
          .then(latestVersion => {
            console.log(latestVersion);    //1.0.6
          });

**Comment by kimxogus** [comment] 2018-01-24 11:28
can you provide your bundle id?
since 2.3.0, app id and app name are not used to retrieve latest version in ios

**Comment by roei1980** [comment] 2018-03-15 07:59
hi there i am use with the 2 functions below 
and all the time i am get error message that said :

"no info about this app"

its came from the two function below..i am really dont know whats the problem .


VersionCheck.needUpdate()
      .then(async (res) => {
        console.log(res.isNeeded); // true
        if (res.isNeeded) {
          Linking.openURL(await VersionCheck.getStoreUrl()); // open store if update is needed.
        }
      })
      .catch((error) => {
        console.error(`VersionCheck.needUpdate - ${error}`);
      });
 


VersionCheck.getLatestVersion()// Automatically choose profer provider using `Platform.select` by device platform.
      .then((latestVersion) => {
        console.log(latestVersion); // 0.1.2
      })
      .catch((error) => {
        console.error(`VersionCheck.getLatestVersion - ${error}`);
      });

==================

VersionCheck.needUpdate()
      .then(async (res) => {
        console.log(res.isNeeded); // true
        if (res.isNeeded) {
          Linking.openURL(await VersionCheck.getStoreUrl()); // open store if update is needed.
        }
      })
      .catch((error) => {
        console.error(`VersionCheck.needUpdate - ${error}`);
      });

**Comment by kimxogus** [comment] 2018-03-16 03:10
`No info about this app` error occurs [here](https://github.com/kimxogus/react-native-version-check/blob/21cd1fcdbdfd1ec0080cc7f0be0fe2913cb5fc40/packages/react-native-version-check/src/providers/appStore.js#L31)

is your app published on app store?

**Comment by roei1980** [comment] 2018-03-18 06:14
yes it is ..

id : 1218814169












*Roei Itzhak*
(m) +972-52-6208994 | Skype: Roei Itzhak
*OnO Apps -* a*+* people. a*+* mobile. | onoapps.com

**Comment by tschoffelen** [comment] 2018-11-30 13:05
I'm closing this, since this seems to be an individual case, most likely caused by the app not being available publicly in the app store.

If I'm wrong in closing this @sukumardv3101 and if this still appears to be an issue, please let me know!

**Closed by tschoffelen** 2018-11-30 13:05 UTC
